### ISSUE TITLE
露娜的S3伤害问题

### ISSUE THREAD

**Issue by BlackYeah** [tyopoyt/epic7-damage-calc#107]
S3有50穿透，但是技能倍率表里没写，伤害计算器数值也不对
![QQ截图20230725115256](https://github.com/tyopoyt/epic7-damage-calc/assets/83203483/2bad7725-c327-4266-9796-8804b1ddf724)

**Comment by tyopoyt** [comment]
我正在使用谷歌翻译，但看起来防御穿透值是正确的。 您是否遇到过损坏错误的问题？
(Used Google translate)
