### ISSUE TITLE
jack-o s1 extra attack multi

### ISSUE THREAD

**Issue by eatyourveg** [tyopoyt/epic7-damage-calc#148]
damage doesnt match up in-game, damage lines up with a ~~rate: 0.85
yes, the skill data sheet says 1.1. not your fault, the dataminer has the wrong number

 s1_extra: {
        name: infoLabel('s1_extra_attack'),
        rate: 1.1,
        pow: 1,
        enhance_from: 's1',
        isExtra: true,
        single: true,
      },

**Comment by tyopoyt** [comment]
I'll reach out to the dataminer to try and reconfirm this value, thanks for the report

**Comment by tyopoyt** [comment]
This was actually due to her extra attack scaling with her s1 enhancements when it should not.  Fixed 👍
