### ISSUE TITLE
increase atk buff and Caster has buff

### ISSUE THREAD

**Issue by Joshua-Son** [tyopoyt/epic7-damage-calc#72]
checking both "increase ask" and "caster has buff" cause double power up
ex: Lone Crescent Bellona, Kise

**Comment by tyopoyt** [comment]
Looks like the number that comes out is correct, just that it's not taking the attack buff to automatically count as a buff.  Probably should fix this so that it'll automatically check that box if you select attack buff. Will probably get around to that at some point

**Comment by tyopoyt** [comment]
Just updated the calc to auto-check and disable the "Caster has buff" box if you check another buff so it's obvious what's going on
