### ISSUE TITLE
Mistakes with pow/enhance

### ISSUE THREAD

**Issue by zacjl** [tyopoyt/epic7-damage-calc#77]
Most skills have pow+enhance=1.3. Outliers do exist, but they are rare. It's possible that some outliers are errors rather than true outliers.

Looking through such skills, there appear to be three categories of such errors:
- Incorrect skill enhance values.
  - Easy to cross-reference with what's displayed in-game. #74 and #76 address these.
- Skills incorrectly benefitting from a skill enhance. I suspect this is the case for:
  - Belian s1 proc
  - SB Aramintha s1 proc
  - Yoonryoung s1 proc
- Incorrect pow. At minimum the following skills are inconsistent with the [skill data spreadsheet](https://docs.google.com/spreadsheets/d/1aqL0Uj26PRW_jAUj8pYaSls_DOuFq30fvwQh8ol74-E/htmlview):

| skill | sheet pow | calc pow | notes |
|---|---|---|---|
| Chloe s2 | 0.9 | 1.2 | atk rate/pow were swapped |
| Lucy s1 | 0.95 | 0.9 |  |
| SC Carrot s3 | 1.1 | 1 | atk rate/pow are swapped relative to Carrot; sheet has 1 atk rate/1 pow for both |
| (SC) Glenn s2 | 0.9 | 1 |  |
| (SC) Helga s2 | 0.95 | 0.9 |  |

**Comment by tyopoyt** [comment]
These have been updated, thanks.
